FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY . /usr/share/nginx/html

RUN sed -i 's/index  index.html index.htm;/index Devops_Intern.html;/' /etc/nginx/conf.d/default.conf
 
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
