version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fusion-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: fusion-frontend
    ports:
      - "8001:80"
    depends_on:
      - backend
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
